import { InfoPageLayout } from "@/components/InfoPageLayout";

export default function Copyright() {
  return (
    <InfoPageLayout
      title="Copyright Policy"
      subtitle="How we respect copyright — and how to report content that doesn't."
      updated="May 22, 2026"
    >
      <section>
        <p>
          TREO TOOL&apos;S respects the intellectual property rights of others and expects
          its users to do the same. This Copyright Policy explains who owns what on this
          site, what you are allowed to do with it, and how copyright holders can report
          alleged infringement.
        </p>
      </section>

      <section>
        <h2 className="text-lg font-semibold text-foreground">1. Our content</h2>
        <p>
          The TREO TOOL&apos;S name, logo, branding, page designs, written copy, and
          source code on this website are © {new Date().getFullYear()} TREO TOOL&apos;S.
          All rights reserved. You may not copy, redistribute, rebrand, or republish them
          without written permission.
        </p>
      </section>

      <section>
        <h2 className="text-lg font-semibold text-foreground">2. Third-party trademarks</h2>
        <p>
          Names such as PDF, JPG, PNG, Microsoft Word (.docx), and any other product or
          company names mentioned on the site are trademarks of their respective owners.
          We mention them only to describe what our tools work with. TREO TOOL&apos;S is
          not affiliated with, endorsed by, or sponsored by any of these companies.
        </p>
      </section>

      <section>
        <h2 className="text-lg font-semibold text-foreground">3. Your content and files</h2>
        <p>
          You retain full ownership of any file you process or any text you type into our
          tools. Because almost everything runs in your browser, we never receive or store
          copies of your files. You are responsible for ensuring you have the right to
          process whatever you upload to a tool.
        </p>
      </section>

      <section>
        <h2 className="text-lg font-semibold text-foreground">4. AI-generated output</h2>
        <p>
          Output produced by the Study Assistant and Notes Maker is generated by an AI
          model and may include material similar to existing works. You are responsible
          for reviewing AI output before using it, especially before submitting it for
          academic credit or republishing it. Many institutions treat unattributed AI
          output as academic dishonesty — please follow your school&apos;s policy.
        </p>
      </section>

      <section>
        <h2 className="text-lg font-semibold text-foreground">5. Reporting infringement (DMCA)</h2>
        <p>
          If you believe that content available on TREO TOOL&apos;S infringes a copyright
          you own or control, please send a notice to{" "}
          <a href="mailto:treotools@gmail.com" className="text-primary hover:underline">treotools@gmail.com</a>{" "}
          with the following information:
        </p>
        <ul className="list-disc pl-5 space-y-1">
          <li>Your full name, postal address, telephone number, and email address.</li>
          <li>A clear description of the copyrighted work you claim has been infringed.</li>
          <li>The exact URL(s) on TREO TOOL&apos;S where the allegedly infringing material is located.</li>
          <li>
            A statement that you have a good-faith belief that the disputed use is not
            authorised by the copyright owner, its agent, or the law.
          </li>
          <li>
            A statement, made under penalty of perjury, that the information in your
            notice is accurate and that you are the copyright owner or authorised to act
            on the owner&apos;s behalf.
          </li>
          <li>Your physical or electronic signature.</li>
        </ul>
        <p>
          We will review valid notices promptly and, where appropriate, remove or disable
          access to the material in question.
        </p>
      </section>

      <section>
        <h2 className="text-lg font-semibold text-foreground">6. Counter-notice</h2>
        <p>
          If you believe content of yours was removed by mistake or misidentification, you
          may send a counter-notice to the same email address with your contact details,
          identification of the removed material, a statement under penalty of perjury that
          you have a good-faith belief the material was removed in error, and your
          consent to the jurisdiction of the appropriate courts.
        </p>
      </section>

      <section>
        <h2 className="text-lg font-semibold text-foreground">7. Repeat-infringer policy</h2>
        <p>
          We may, in appropriate circumstances and at our discretion, restrict or
          terminate access to the Service for users who repeatedly infringe the
          intellectual property rights of others.
        </p>
      </section>

      <section>
        <h2 className="text-lg font-semibold text-foreground">8. Permissions and licensing</h2>
        <p>
          To request permission to use the TREO TOOL&apos;S name, logo, or content, please
          reach out via our{" "}
          <a href="/contact" className="text-primary hover:underline">Contact page</a>.
        </p>
      </section>
    </InfoPageLayout>
  );
}
